### ISSUE TITLE
Ticking Entity crash?

### ISSUE THREAD

**Issue by thetaCriterion** [TheXFactor117/Levels#100] opened 2017-02-28 03:28 UTC
A random crash happened, and I don't think I have any insight as to why. The crash report is yelling about Levels, and maybe arrows? I'm not sure I know what I'm seeing here.

Crash report here: http://pastebin.com/wF1Q4PZU

This was on the 1.10.2-r1.2.3 version.

**Comment by TheXFactor117** [comment] 2017-02-28 18:17
Are you getting shot with an arrow? I think I know the issue and can make a fix, but it won't be a certain fix because I'm not sure I can reproduce the crash.

**Comment by TheXFactor117** [comment] 2017-02-28 18:31
Should be fixed in r1.2.4

**Closed by TheXFactor117** 2017-02-28 18:31 UTC
